services:

  web:
    image: ghcr.io/mijonofthemoon/django-project:master
    ports:
      - "8000:8000"
    env_file: .env_web
    depends_on:
      - db

  db:
    image: postgres:16.9-alpine
    ports:
      - "5432:5432"
    env_file: .env_db